name = "on-chain/scripts"
version = "0.0.0"
compiler = "v1.0.20"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'on-chain/oscripts'"

[repository]
user = "on-chain"
project = "scripts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v1.7.0"
source = "github"

[config]
